### ISSUE TITLE
Улучшить topology.toml

### ISSUE THREAD

**Issue by lowitea** [picodata/pike#1]
```toml
[tiers.default]
instances = 2
replication_factor = 2

[[tiers.default.services]]
name = "main"
plugin = "plugin_name"
```
в

```toml
[tier.default]
instances = 2
replication_factor = 2

[[tier.default.service]]
name = "main"
plugin = "plugin_name"
```
