### ISSUE TITLE
`can_vote` не передаётся в пикодату

### ISSUE THREAD

**Issue by aensidhe** [picodata/pike#147]
При запуске кластера с конфигом:

```toml
[tier.default]
replicasets = 4
replication_factor = 2
can_vote = false

[tier.extra]
replicasets = 1
replication_factor = 2
```

Тир default всё равно имеет `can_vote = true`

**Comment by lowitea** [comment]
Да, это ожидаемо. Все настройки пикодаты в файле picodata.yml. В топологии настройки количества инстансов и где включать плагин.

**Comment by aensidhe** [comment]
А как мне настроить разный `can_vote` для разных тиров? @lowitea

**Comment by lowitea** [comment]
Примерно вот так

```yaml
# picodata.yaml

cluster:
  name: "sandbox"
  tier:
    default:
      can_vote: true
    another:
      can_vote: false
```

```sql
select * from _pico_tier;
+---------+--------------------+----------+-------------------------------+------------------------------+---------------------+--------------+
| name    | replication_factor | can_vote | current_vshard_config_version | target_vshard_config_version | vshard_bootstrapped | bucket_count |
+=============================================================================================================================================+
| another | 2                  | false    | 0                             | 0                            | false               | 3000         |
|---------+--------------------+----------+-------------------------------+------------------------------+---------------------+--------------|
| default | 2                  | true     | 3                             | 3                            | true                | 3000         |
+---------+--------------------+----------+-------------------------------+------------------------------+---------------------+--------------+
(2 rows)
```
