### ISSUE TITLE
Я как пользователь хочу устанавливать плагин по урлу

### ISSUE THREAD

**Issue by lowitea** [picodata/pike#156]
Можно разрешить использовать в path uri (file:, http:)
  ```toml
  [plugin.sirin]
  path = "http://picodata.io/path/to/plugin/sirin/0.1.0/sirin.zip"
  #path = "file:../../../path/to/some/folder/sirin/sirin-plugin"
  ````
  Или отдельный параметр `url`, но проверять что задано только что-то одно
  ```toml
  [plugin.sirin]
  url = "http://picodata.io/path/to/plugin/sirin/0.1.0/sirin.zip"
  ````
  Не понятно как передавать креды не засветив их в гите. Переменные? Или отдельный файл с кредами?
