### ISSUE TITLE
Добавить возможность задавать конфигурацию каждому инстансу

### ISSUE THREAD

**Issue by aensidhe** [picodata/pike#48]
### Проблема

Некоторые плагины, например, радикс, открывают свои порты на прослушивание.

Если инстансов в кластере более одного, надо иметь возможность, задавать им свои порты для этого:

`RADIX_ADDR=0.0.0.0:7301`, `RADIX_ADDR=0.0.0.0:7302` и т.д.

### Предложение

Сделать как строковую интерполяцию для индекса, так и арифметическое сложение. Второе приоритетнее, чем первое.

```toml
# topology.yoml

[instance_environment]
RADIX_ADDR=7300+$index
```
