### ISSUE TITLE
поправить нумерование инстансов

### ISSUE THREAD

**Issue by alrsorokin** [picodata/pike#70]
имею топологию вида
```toml
[tier.proto]
replicasets = 1
replication_factor = 1

[tier.engine]
replicasets = 1
replication_factor = 1
```
которая казалось бы должна дать инстансы вида:
```
proto-i1 (или proto-1)
engine-i1 (или engine-1)
```

при запуске наблюдаю логи вида:
```sh
proto-i2: 2025-02-21 11:00:20.879 
engine-i1: 2025-02-21 11:00:20.879
```

в `cluster/tmp` следующие директории:
```sh
i1
i2
```
ну не сказать что сложно определить кто есть кто, но путаница присутсвует, осоебнно что `tier.proto` был объявлен первым и сервис зарегистрирован первым
